<a href="https://colab.research.google.com/github/bigyandulal2/datascience/blob/main/employes-Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
df=pd.read_csv("Employees-Practice.csv");
from google.colab import drive
drive.mount('/content/drive')
df.to_csv("/content/drive/MyDrive/Employees-Practice.csv", index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
df.head()

   EmpID Department        City  Salary  Experience
0      1         IT   Kathmandu   60000           3
1      2         HR   Kathmandu   45000           2
2      3         IT     Pokhara   70000           5
3      4      Sales     Pokhara   40000           1
4      5         HR  Biratnagar   48000           3

In [16]:
#Average Salary per Department?
avg_salary_per_department=df.groupby("Department")["Salary"].mean()
print(avg_salary_per_department);

Department
HR       46500.0
IT       65000.0
Sales    40000.0
Name: Salary, dtype: float64

In [17]:
# Total Salary cost per City?
total_salary_per_city=df.groupby("City")["Salary"].sum()
print(total_salary_per_city)

City
Biratnagar     86000
Kathmandu     212000
Pokhara       110000
Name: Salary, dtype: int64

In [18]:
# Average Experience per Department?
avg_experience_per_department=df.groupby("Department")["Experience"].mean().round(1);
print(avg_experience_per_department)

Department
HR       2.5
IT       4.0
Sales    1.3
Name: Experience, dtype: float64

In [23]:
# average salary of IT department for every IT employee?
df["dept_avg_salary"]=df.groupby("Department")["Salary"].transform("mean")

In [24]:
df.columns

Index(['EmpID', 'Department', 'City', 'Salary', 'Experience',
       'dept_avg_salary'],
      dtype='object')

In [25]:
df.head()

   EmpID Department        City  Salary  Experience  dept_avg_salary
0      1         IT   Kathmandu   60000           3          65000.0
1      2         HR   Kathmandu   45000           2          46500.0
2      3         IT     Pokhara   70000           5          65000.0
3      4      Sales     Pokhara   40000           1          40000.0
4      5         HR  Biratnagar   48000           3          46500.0

In [ ]:
df["dept_avg_salary"]